language: ruby
rvm:
- 2.1

script: ./scripts/cibuild

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

notifications:
   slack: sensorberg:bYfkpm6TExFzF5gdpQz2IHDh
